/**
 * Longbridge US 设计语言 · Design Tokens (W3C DTCG SSOT)
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND
 * Source: tokens.json (W3C DTCG)
 * Build:  node scripts/build-tokens.mjs
 */

export const color = {
  "bg-1": "#0a0e19",
  "bg-2": "#232630",
  card: "#232630",
  "card-2": "#181b26",
  soft: "#1a1e28",
  "tab-active": "#ffffff",
  line: "#3b3e47",
  stroke: "#2c3039",
  "line-button": "#363a47",
  "fg-1": "#ffffff",
  "fg-2": "#9d9fa3",
  "fg-3": "#60626a",
  "fg-4": "#363a47",
  "fg-inverse": "#0a0e19",
  "brand-1": "#00f0c4",
  "brand-2": "#09252a",
  "brand-3": "#203a3f",
  "brand-soft": "rgba(0, 240, 196, 0.1)",
  "brand-glow": "rgba(0, 240, 196, 0.22)",
  accent: "#00f0c4",
  "accent-soft": "rgba(0, 240, 196, 0.1)",
  "accent-glow": "rgba(0, 240, 196, 0.22)",
  up: "#00ada2",
  "up-soft": "rgba(0, 173, 162, 0.14)",
  down: "#ff3a75",
  "down-soft": "rgba(255, 58, 117, 0.14)",
  flat: "#60626a",
  error: "#f7415f",
  warn: "#ff9728",
  safe: "#00cc92",
  info: "#2a99fe",
  "chart-blue": "#0cb6ff",
  "chart-purple": "#5a74ff",
  "chart-yellow": "#ffa61f",
  "chart-green": "#35c15c",
  "chart-pink": "#ec54b8",
  "chart-red": "#de3150",
  "chart-orange": "#ff7128",
  "chart-grey": "#c1d0e6",
  "chart-bg": "#2c3039",
  chatbox: "#00a9a9",
  "chatbox-at": "#00f0c4",
  "avatar-fill": "rgba(204, 204, 204, 0.6)",
  mask: "rgba(10, 14, 25, 0.6)",
  hairline: "#2c3039",
  "hairline-strong": "#3b3e47",
  border: "#2c3039",
  divider: "#3b3e47",
} as const;

export const fs = {
  "3xs": "0.5rem",
  "2xs": "0.5625rem",
  xs: "0.625rem",
  sm: "0.6875rem",
  base: "0.75rem",
  md: "0.8125rem",
  lg: "0.875rem",
  xl: "1.125rem",
  "2xl": "1.5rem",
  "3xl": "2.25rem",
  "4xl": "3rem",
  "6xl": "3.75rem",
} as const;

export const fw = {
  normal: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
} as const;

export const lh = {
  none: 1,
  tight: 1.2,
  dense: 1.3,
  snug: 1.4,
  normal: 1.5,
  "relaxed-tight": 1.55,
  "relaxed-snug": 1.6,
  relaxed: 1.65,
} as const;

export const ls = {
  tightest: "-0.04em",
  tight: "-0.02em",
  snug: "-0.01em",
  normal: "0",
  wide: "0.04em",
  "caps-narrow": "0.06em",
  wider: "0.1em",
} as const;

export const sp = {
  "0": "0",
  "1": "0.25rem",
  "2": "0.5rem",
  "3": "0.75rem",
  "4": "1rem",
  "5": "1.25rem",
  "6": "1.5rem",
  "8": "2rem",
  "10": "2.5rem",
  "12": "3rem",
  "16": "4rem",
  px: "1px",
  "0-5": "0.125rem",
  "1-5": "0.375rem",
  "card-x": "1rem",
  "card-y": "0.75rem",
  section: "1rem",
  row: "0.375rem",
  inline: "0.5rem",
  stack: "0.75rem",
} as const;

export const r = {
  none: "0",
  xs: "0.125rem",
  sm: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  full: "9999px",
} as const;

export const bw = {
  "0": "0",
  "1": "1px",
  "2": "2px",
  "3": "3px",
  "4": "4px",
} as const;

export const sh = {
  none: "none",
  flat: "0 1px 2px rgba(0, 0, 0, 0.3)",
  raised: "0 2px 8px rgba(0, 0, 0, 0.35), 0 4px 16px rgba(0, 0, 0, 0.2)",
  popover: "0 4px 16px rgba(0, 0, 0, 0.4), 0 12px 32px rgba(0, 0, 0, 0.3)",
  modal: "0 8px 32px rgba(0, 0, 0, 0.5), 0 24px 64px rgba(0, 0, 0, 0.4)",
  "focus-ring": "0 0 0 2px rgba(0, 240, 196, 0.4)",
  "inset-pressed": "inset 0 1px 2px rgba(0, 0, 0, 0.3)",
  "glow-up": "0 0 8px rgba(0, 173, 162, 0.4)",
  "glow-down": "0 0 8px rgba(255, 58, 117, 0.4)",
} as const;

export const op = {
  transparent: 0,
  "hover-bg": 0.05,
  "overlay-bg": 0.1,
  disabled: 0.4,
  muted: 0.6,
  emphasis: 0.85,
  full: 1,
} as const;

export const dur = {
  instant: "50ms",
  fast: "80ms",
  base: "150ms",
  modal: "200ms",
  slow: "240ms",
  flash: "300ms",
  slower: "400ms",
} as const;

export const ease = {
  linear: "linear",
  out: "cubic-bezier(0.16, 1, 0.3, 1)",
  "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
  snap: "cubic-bezier(0.22, 1, 0.36, 1)",
  decelerate: "cubic-bezier(0, 0, 0.2, 1)",
  accelerate: "cubic-bezier(0.4, 0, 1, 1)",
  bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
} as const;

export const z = {
  base: 0,
  sticky: 10,
  dropdown: 25,
  overlay: 30,
  fab: 35,
  modal: 40,
  popover: 60,
  tooltip: 70,
  toast: 80,
  debug: 9999,
} as const;

export const font = {
  sans: "\"Inter\", -apple-system, BlinkMacSystemFont, \"PingFang SC\", \"Noto Sans SC\", system-ui, sans-serif",
  num: "\"JetBrains Mono\", \"SF Mono\", Menlo, Consolas, monospace",
} as const;

export const component = {
  "button-height-sm": "24px",
  "button-height-md": "32px",
  "button-height-lg": "40px",
  "button-px-sm": "8px",
  "button-px-md": "12px",
  "button-px-lg": "16px",
  "input-height": "32px",
  "input-px": "12px",
  "card-px": "1rem",
  "card-py": "0.75rem",
  "table-row-height": "32px",
  "table-row-height-dense": "24px",
  "table-header-height": "28px",
  "topbar-height": "32px",
  "footer-bar-height": "32px",
  "tab-height": "40px",
  "checkbox-size": "16px",
  "radio-size": "16px",
  "switch-width": "32px",
  "switch-height": "18px",
  "avatar-sm": "20px",
  "avatar-md": "32px",
  "avatar-lg": "48px",
} as const;

export const breakpoint = {
  sm: "640px",
  md: "768px",
  lg: "1024px",
  xl: "1280px",
  "2xl": "1536px",
} as const;

export const container = {
  max: "1280px",
  "max-wide": "1480px",
  "max-narrow": "920px",
} as const;

export const icon = {
  "2xs": "10px",
  xs: "12px",
  sm: "14px",
  md: "16px",
  lg: "20px",
  xl: "24px",
  "2xl": "32px",
} as const;

export const tokens = { color, fs, fw, lh, ls, sp, r, bw, sh, op, dur, ease, z, font, component, breakpoint, container, icon } as const;
