#!/usr/bin/env node
/**
 * Design Token Generator
 *
 * 读 tokens.json (W3C DTCG SSOT),生成消费格式:
 *   - tokens.css   (CSS 变量 + Tailwind @theme inline 映射)
 *   - tokens.ts    (TypeScript 常量,类型安全)
 *
 * tokens.json 本身是 SSOT(W3C DTCG 行业标准),不需要派生。
 * 设计工具(Figma / Tokens Studio)可直接读写 tokens.json。
 *
 * Usage:  node scripts/build-tokens.mjs
 *
 * Node ≥ 18,无外部依赖。
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(__dirname, "..", "tokens");
const SRC = join(TOKENS_DIR, "tokens.json");

// ───────────────────────────────────────────────────────────────────────
// Tailwind 4 namespace mapping
//   group → Tailwind theme prefix
// 没在此表的 group 不会出现在 @theme inline(走 CSS var)
// ───────────────────────────────────────────────────────────────────────
const TW_NAMESPACE = {
  color: "--color-",
  fs:    "--text-",
  fw:    "--font-weight-",
  lh:    "--leading-",
  ls:    "--tracking-",
  r:     "--radius-",
  sh:    "--shadow-",
  ease:  "--ease-",
  font:  "--font-",
};

// CSS :root prefix per group(扁平命名)
const CSS_ROOT_PREFIX = {
  color:      "--",           // 不带前缀:--bg-1 / --brand-1
  fs:         "--fs-",
  fw:         "--fw-",
  lh:         "--lh-",
  ls:         "--ls-",
  sp:         "--sp-",
  r:          "--r-",
  bw:         "--bw-",
  sh:         "--sh-",
  op:         "--op-",
  dur:        "--dur-",
  ease:       "--ease-",
  z:          "--z-",
  font:       "--font-",
  component:  "--cmp-",
  breakpoint: "--bp-",
  container:  "--ctn-",
  icon:       "--icon-",
};

// font-size alias(项目语义命名,只用于 Tailwind utility)
const FS_ALIAS = {
  caps:    "xs",
  data:    "base",
  section: "md",
};

// ───────────────────────────────────────────────────────────────────────
// Util — 处理 W3C DTCG 格式
// ───────────────────────────────────────────────────────────────────────

/** 取 $value,处理 token alias reference 形如 "{color.brand-1}" */
function resolveValue(value, src) {
  if (typeof value !== "string") return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const parts = path.split(".");
    let cur = src;
    for (const p of parts) cur = cur && cur[p];
    if (cur && typeof cur === "object" && "$value" in cur) {
      return resolveValue(cur.$value, src);
    }
    return `{${path}}`; // 未解析,保留原样
  });
}

/** 给 CSS 输出用:保留 var() 引用(更易调试) */
function valueForCSS(value, src) {
  if (typeof value !== "string") return value;
  // 把 {color.brand-1} 转成 var(--brand-1)
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const parts = path.split(".");
    if (parts.length === 2) {
      const [group, name] = parts;
      const prefix = CSS_ROOT_PREFIX[group];
      if (prefix) {
        const varName = prefix === "--" ? `--${name}` : `${prefix}${name}`;
        return `var(${varName})`;
      }
    }
    // fallback:解析为字面值
    return resolveValue(`{${path}}`, src);
  });
}

/** 给 TS / JSON 输出用:解析为字面值 */
function valueForLiteral(value, src) {
  return resolveValue(value, src);
}

/** 遍历 group,产出 [key, valueForCSS, valueForLiteral, desc] */
function* iterEntries(group, src) {
  for (const [key, entry] of Object.entries(group)) {
    if (key.startsWith("$")) continue; // 跳过 group 级 metadata
    if (!entry || typeof entry !== "object" || !("$value" in entry)) continue;
    yield {
      key,
      css: valueForCSS(entry.$value, src),
      literal: valueForLiteral(entry.$value, src),
      desc: entry.$description || null,
      type: entry.$type,
    };
  }
}

// ───────────────────────────────────────────────────────────────────────
// CSS Generator
// ───────────────────────────────────────────────────────────────────────
function buildCSS(src) {
  const out = [];

  out.push(`/* ═════════════════════════════════════════════════════════════════════════`);
  out.push(` * ${src.$description}`);
  out.push(` *`);
  out.push(` * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND`);
  out.push(` * Source: tokens.json (W3C DTCG)`);
  out.push(` * Build:  node scripts/build-tokens.mjs`);
  out.push(` *`);
  out.push(` * Theme:   ${src.$theme || "dark"}`);
  out.push(` * Updated: ${src.$updated}`);
  out.push(` * ═════════════════════════════════════════════════════════════════════════ */`);
  out.push("");
  out.push(":root {");
  if (src.$theme === "dark") out.push("  color-scheme: dark;");
  else if (src.$theme === "light") out.push("  color-scheme: light;");
  out.push("");

  for (const [groupName, group] of Object.entries(src)) {
    if (groupName.startsWith("$")) continue;
    const prefix = CSS_ROOT_PREFIX[groupName];
    if (!prefix) continue;

    out.push(`  /* ${groupName} */`);
    for (const { key, css, desc } of iterEntries(group, src)) {
      const varName = prefix === "--" ? `--${key}` : `${prefix}${key}`;
      const comment = desc ? `  /* ${desc} */` : "";
      out.push(`  ${varName}: ${css};${comment}`);
    }
    out.push("");
  }

  out.push("}");
  out.push("");

  // @theme inline
  out.push("/* ═════════════════════════════════════════════════════════════════════════");
  out.push(" * Tailwind 4 @theme — token 暴露为 utility class");
  out.push(" * 自动从 TW_NAMESPACE 映射生成");
  out.push(" * ═════════════════════════════════════════════════════════════════════════ */");
  out.push("@theme inline {");

  for (const [groupName, group] of Object.entries(src)) {
    if (groupName.startsWith("$")) continue;
    const twPrefix = TW_NAMESPACE[groupName];
    if (!twPrefix) continue;

    out.push(`  /* ${groupName} → ${twPrefix}* */`);
    for (const { key, literal } of iterEntries(group, src)) {
      out.push(`  ${twPrefix}${key}: ${literal};`);
    }

    // font-size alias
    if (groupName === "fs") {
      out.push(`  /* fs alias(项目语义命名) */`);
      for (const [aliasKey, targetKey] of Object.entries(FS_ALIAS)) {
        const target = src.fs[targetKey];
        const val = target ? resolveValue(target.$value, src) : "";
        out.push(`  --text-${aliasKey}: ${val};`);
      }
    }
    out.push("");
  }

  out.push("}");
  out.push("");

  return out.join("\n");
}

// ───────────────────────────────────────────────────────────────────────
// TS Generator
// ───────────────────────────────────────────────────────────────────────
function buildTS(src) {
  const out = [];

  out.push(`/**`);
  out.push(` * ${src.$description}`);
  out.push(` *`);
  out.push(` * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND`);
  out.push(` * Source: tokens.json (W3C DTCG)`);
  out.push(` * Build:  node scripts/build-tokens.mjs`);
  out.push(` */`);
  out.push("");

  for (const [groupName, group] of Object.entries(src)) {
    if (groupName.startsWith("$")) continue;
    out.push(`export const ${groupName} = {`);
    for (const { key, literal } of iterEntries(group, src)) {
      const k = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
      const v = typeof literal === "number" ? literal : JSON.stringify(literal);
      out.push(`  ${k}: ${v},`);
    }
    out.push(`} as const;`);
    out.push("");
  }

  const groups = Object.keys(src).filter((k) => !k.startsWith("$"));
  out.push(`export const tokens = { ${groups.join(", ")} } as const;`);
  out.push("");

  return out.join("\n");
}

// ───────────────────────────────────────────────────────────────────────
// Run
// ───────────────────────────────────────────────────────────────────────
async function main() {
  console.log("→ Reading tokens.json (W3C DTCG SSOT)");
  const src = JSON.parse(await readFile(SRC, "utf-8"));

  // 简单 schema 校验:每个 token 必须有 $type 和 $value
  let issues = 0;
  for (const [groupName, group] of Object.entries(src)) {
    if (groupName.startsWith("$")) continue;
    if (!group || typeof group !== "object") continue;
    for (const [key, entry] of Object.entries(group)) {
      if (key.startsWith("$")) continue;
      if (!entry || typeof entry !== "object") continue;
      if (!("$value" in entry)) {
        console.warn(`  ⚠ ${groupName}.${key} 缺少 $value`);
        issues++;
      }
      if (!("$type" in entry)) {
        console.warn(`  ⚠ ${groupName}.${key} 缺少 $type`);
        issues++;
      }
    }
  }
  if (issues > 0) {
    console.warn(`  共 ${issues} 处不规范,但仍继续生成`);
    console.log();
  }

  const outputs = [
    ["tokens.css", buildCSS(src)],
    ["tokens.ts",  buildTS(src)],
  ];

  for (const [name, content] of outputs) {
    const path = join(TOKENS_DIR, name);
    await writeFile(path, content, "utf-8");
    const lines = content.split("\n").length;
    const kb = (content.length / 1024).toFixed(1);
    console.log(`✓ Wrote ${name.padEnd(12)} ${lines.toString().padStart(4)} lines  ${kb.padStart(5)} KB`);
  }

  console.log("");
  console.log("✅ Generated from tokens.json (W3C DTCG SSOT)");
  console.log("   改 token: 改 tokens.json,然后重跑此脚本");
}

main().catch((err) => {
  console.error("✗ Build failed:", err);
  process.exit(1);
});
